# active profile
spring:
   application:
     name: mes-project
   profiles:
      active: development
      
---
#
# common configuration
#
spring:
   mvc:
      # path pattern used for static resources
      static-path-pattern: /assets/**

      # whether a "NoHandlerFoundException" should be thrown if no handler was found to process a request
      throw-exception-if-no-handler-found: true
         
   web:
      resources:
         # Locations of static resources
         static-locations: classpath:/assets/
         
   # template engine: thymeleaf    
   thymeleaf:
      prefix: classpath:templates/
      check-template-location: true
      mode: HTML
      suffix: .html
      cache: false
         
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

         
---
#
# development profile configuration
#
spring:
   config:
      activate:
         on-profile: development
         
   # devtools enabled
   devtools:
      livereload:
         enabled: true

   # datasource
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://34.64.199.56:5432/poscoict?characterEncoding=UTF-8&serverTimezone=UTC
      username: poscoict
      password: 1234

# server
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
# logging
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

         
---
#
# production profile configuration
#
spring:
   config:
      activate:
         on-profile: production

   # datasource
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://34.64.199.56:5432/poscoict?characterEncoding=UTF-8&serverTimezone=UTC
      username: poscoict
      password: 1234
         
# server
server:
   port: 8000
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
         
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
   file:
      name: logs/${spring.application.name}.log
      max-history: 30
   level:
      root: INFO
      com:
         poscoict:
            mesproject:
               exception: ERROR
         

